/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.h2o.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public String runConnector(String authType) {
        Path workingDir = Paths.get(".").toAbsolutePath();
        try {
            String[] commands = {
                    "java",
                    "-Ddai.connectors.log.dir=" + workingDir.resolve("build/logs"),
                    "-cp",
                    "h2oai-dai-connectors.jar:" + workingDir.resolve("conf").resolve(authType.toLowerCase()),
                    "ai.h2o.dai.connectors.HiveConnectorCli",
                    "--user=sajith",
                    "--appUser=",
                    "--keyTabPath=",
                    "--dst=" + workingDir.resolve("build/results_" + System.currentTimeMillis()),
                    "--authType=" + authType,
                    "--query=select 1",
                    "--coreSiteXmlPath=conf",
                    "--command=query"
            };
            Process p = new ProcessBuilder(commands)
                    .directory(Paths.get("").toAbsolutePath().toFile())
                    .redirectErrorStream(true)
                    .start();
            p.waitFor();
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
            StringBuilder result = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                result.append(inputLine);
            }
            in.close();
            return result.toString();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            return e.getMessage();
        }
    }

    public static void main(String[] args) {
        System.out.println("===================================");
        System.out.println(new App().runConnector("NOAUTH"));
        System.out.println("===================================");
    }
}
