/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ai.h2o.example;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Path;
import java.nio.file.Paths;

public class ConnectorRunner {
    public String run(Parameters parameters) {
        Path workingDir = Paths.get("").toAbsolutePath();
        try {
            String[] commands = {
                    "java",
                    "-Ddai.connectors.log.dir=" + workingDir.resolve("build/logs"),
                    "-Djava.security.krb5.conf=" + System.getProperty("java.security.krb5.conf"),  // MiniKdc sets this
                    "-cp",
                    "h2oai-dai-connectors.jar:" + parameters.getConfDir(),
                    "ai.h2o.dai.connectors.HiveConnectorCli",
                    "--user=" + parameters.getUser(),
                    "--appUser=" + parameters.getAppUser(),
                    "--keyTabPath=" + parameters.getKeyTabPath(),
                    "--dst=" + parameters.getDestinationDir(),
                    "--authType=" + parameters.getAuthType(),
                    "--query=" + parameters.getQuery(),
                    "--coreSiteXmlPath=" + parameters.getConfDir(),
                    "--command=query"
            };
            Process p = new ProcessBuilder(commands)
                    .directory(workingDir.toFile())
                    .redirectErrorStream(true)
                    .start();
            p.waitFor();
            BufferedReader in = new BufferedReader(new InputStreamReader(p.getInputStream()));
            StringBuilder result = new StringBuilder();
            String inputLine;
            while ((inputLine = in.readLine()) != null) {
                result.append(inputLine);
            }
            in.close();
            return result.toString();
        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
            return e.getMessage();
        }
    }

    public static void main(String[] args) {
        System.out.println("===================================");
        final Parameters parameters = Parameters.builder()
                .setAuthType("NOAUTH")
                .setQuery("show databases")
                .build();
        System.out.println(new ConnectorRunner().run(parameters));
        System.out.println("===================================");
    }
}
